apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: okteto/client:buildTag
          env:
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: nextauth-url
            - name: NEXTAUTH_URL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: nextauth-url-internal
            - name: NEXT_PUBLIC_GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: github-client-id
            - name: NEXT_PUBLIC_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-client-secret
                  key: github-client-secret
            - name: NEXT_PUBLIC_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: jwt-key
            - name: NEXT_PUBLIC_CLIENT_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: nextauth-url-internal
            - name: NEXT_PUBLIC_PAYMENTS_RELATIVEURL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: client-payments-relativeurl
            - name: NEXT_PUBLIC_TICKETS_RELATIVEURL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: client-tickets-relativeurl
            - name: NEXT_PUBLIC_ORDERS_RELATIVEURL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: client-orders-relativeurl
            - name: NEXT_PUBLIC_STRIPE_PUB
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: client-stripe-pub
          resources:
            requests:
              memory: '250Mi'
              cpu: '125m'
            limits:
              memory: '500Mi'
              cpu: '250m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
