apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: okteto/tickets:buildTag
          env:
            - name: GATEWAY_DGRAPH_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-dgraph-config
                  key: gateway-dgraph-url
          resources:
            requests:
              memory: '125Mi'
              cpu: '100m'
            limits:
              memory: '250Mi'
              cpu: '200m'
      initContainers:
        - name: tickets-wait-for-gateway-dgraph
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo Starting to wait for gateway-dgraph to run
              response_code=0
              while [ ${response_code} -ne 400 ]
              do
                echo Waiting for gateway-dgraph to run...
                sleep 5
                response_code=$(curl -sw ${response_code} http://gateway-dgraph-srv:5000/graphql -o /dev/null) -ne 400 ]
                echo Response Code is ${response_code}
              done
              echo gateway-dgraph is running
          resources:
            requests:
              memory: '125Mi'
              cpu: '100m'
            limits:
              memory: '250Mi'
              cpu: '200m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4001
      targetPort: 4001
