name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          name: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          timeout: 10m

      - name: Publish GraphQL Dgraph schema
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway-dgraph \
            --routing-url http://dgraph-srv:8080/graphql \
            --schema gateway-dgraph/src/dgraph/schema.graphql \
            --name dgraph \
            --convert

      - name: Publish GraphQL schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert